language: ruby
rvm: 2.4.2
gemfile:
  - Gemfile
sudo: false
before_install: gem install bundler
script: bundle exec rake test
env:
  - KMS_KEY_ID=insecure-test-key
notifications:
  email:
    on_success: never
    on_failure: change
